name: SBS Electron

on:
  push:
    branches:
      - master
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 16.15.1
      - name: clear cache
        run: npm cache clean --force
      - name: update npm
        run: npm update -g npm
      - name: update gyp
        run: npm install --global node-sass@latest
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2017
        run: npm config set msvs_version 2017
      - name: install depedencies
        run: npm install --force
      - name: rebuild
        run: npm rebuild
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
      - name: test build
        run: npm run build-s3
