name: SBS Electron

on:
  push:
    branches:
      - master
jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 16.15.1
      - name: install node_gyp
        run: npm install npm node-gyp
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2017
        run: npm config set msvs_version 2017
      - name: install depedencies
        run: npm install 
      - name: rebuild
        run: npm rebuild
      - name: set access key
        run: set AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
      - name: set secret key
        run: set AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: test build
        run: npm run build-s3
